<?php

namespace ElsassSeeraiwer\ESMenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuConfigRepository extends EntityRepository
{
}
